---
config:
  imagesPath: img/characters/
characters:
  game:
    name: ""
    color: white
  player:
    style:
      color: orange
    name: You
  salva:
    style:
      color: purple
    name: Salva
  silence:
    style:
      color: yellow
    name: Silence
  lore:
    style:
      color: red
    name: Lore
