options:
  diceRange: [1, 20]
  diceCount: 1
  extraPointsPerLevel: 1
  extraDicePerLevel: 0
  successOnRollsBelowThreshold: false
  showDifficultyText: true
  showDifficultyNumber: true
  showDifficultyWithoutModifiers: false
  totalRollIsHighest: false
  totalRollIsLowest: false
  difficultyText:
    - [1, "Critical Miss"]
    - [2, "Low"]
    - [10, "Medium"]
    - [15, "High"]
    - [20, "Critical Hit"]
skillChecks: {}
